require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Include:
    - Gemfile
    - Rakefile
    - config.ru
    - lib/**/*.rake
    - '**/*.rb'
  Exclude:
    - 'vendor/**/*'
    - 'bin/*'
    - db/schema.rb
  NewCops: enable

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*'
    - db/schema.rb
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - db/schema.rb

Style/WordArray:
  Exclude:
    - db/schema.rb

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - db/schema.rb

Rails/FilePath:
  Enabled: false

Rails/Output:
  Exclude:
    - db/seeds.rb

Rails/BulkChangeTable:
  Enabled: false
